# Generated by Django 4.2 on 2024-07-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoicing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="phone",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
