# Generated by Django 4.2 on 2024-07-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoicing", "0003_alter_company_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="city",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
