# Generated by Django 4.2 on 2024-07-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoicing", "0004_company_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="type_dealer_customer",
            field=models.CharField(
                blank=True,
                choices=[("dealer", "Dealer"), ("customer", "Customer")],
                max_length=20,
                null=True,
            ),
        ),
    ]
