# Generated by Django 4.2 on 2024-07-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoicing", "0005_company_type_dealer_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="type_dealer_customer",
            field=models.CharField(
                choices=[
                    (None, "test affichage"),
                    ("dealer", "Dealer"),
                    ("customer", "Customer"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
