# Generated by Django 4.2 on 2024-07-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoicing", "0008_remove_company_type_customer_box_customer_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="type",
            field=models.CharField(
                choices=[
                    (None, "Sélectionnez..."),
                    ("srl", "SRL"),
                    ("sa", "SA"),
                    ("sc", "SC"),
                    ("snc", "SNC"),
                    ("scomm", "SComm"),
                    ("soc. simple", "Soc. Simple"),
                    ("autre", "Autre"),
                ],
                default="srl",
                max_length=15,
            ),
        ),
    ]
